version: "3"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - sp_seo_tool_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sp_seo_tool_network

  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    volumes:
      - .:/usr/src/app
    networks:
      - sp_seo_tool_network
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    command: yarn run start:dev
#    env_file:
#      - ./.env

  redis:
    image: redis
    networks:
      - sp_seo_tool_network
    ports:
      - "6379:6379"
    volumes:
      - sp_seo_tool_redis:/data
    command: redis-server --appendonly yes


networks:
  sp_seo_tool_network:

volumes:
  sp_seo_tool_db:
  sp_seo_tool_redis: